export default {
  zona: "",
  provincia: "",
  canton: "",
  parroquia: "",
  sector: "",
  referencia: "",
  principal: "",
  secundaria: "",
  nombreInfraestructura: "",
  fechaInspeccion: "",
  horaInspeccion: "",
  tipoServicio: "",
  otroTipoServicio: "",
  institucion: "",
  nombreRepresentante: "Edison Mora",
  celularRepresentante: "+593992556793",
  convencionalRepresentante: "042348515",
};
